[package]
name = "geometry"
version = "0.1.0"
edition = "2021"


[features]
direct2d = ["windows"]

[dependencies]


[dependencies.windows]
optional = true
path = "../../windows-rs/crates/libs/windows"
features = [
    "Win32_Graphics_Direct2D"
]